media:
  input: webp-images/content
  output: /webp-images/content

content:
  - name: news
    label: News & Updates
    type: collection
    path: content/news
    fields:
      - name: title
        label: Article Title
        type: string
        required: true
      - name: date
        label: Publication Date
        type: string
        required: true
      - name: description
        label: SEO Meta Description
        type: string
      - name: body
        label: Content Body
        type: rich-text
        required: true
